## Project
name: tasty_bytes
version: "1.0"
config-version: 2
profile: tasty_bytes

## Sources
model-paths: [models]
analysis-paths: [analysis]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

## Target
target-path: target
clean-targets: [target, dbt_modules]

## Models
models:
  tasty_bytes:
    10_historized_landing:
      +materialized: view
      +schema: >
        {%- if target.name == "dev" -%}
          {{ env_var('SNOWFLAKE_SCHEMA') }}
        {%- else -%}
          HISTORIZED_LANDING
        {%- endif -%}
    20_base:
      +materialized: view
      +schema: >
        {%- if target.name == "dev" -%}
          {{ env_var('SNOWFLAKE_SCHEMA') }}
        {%- else -%}
          BASE
        {%- endif -%}
    30_extended_base:
      +materialized: view
      +schema: >
        {%- if target.name == "dev" -%}
          {{ env_var('SNOWFLAKE_SCHEMA') }}
        {%- else -%}
          EXTENDED_BASE
        {%- endif -%}
    50_businesscore:
      +materialized: table
      +schema: >
        {%- if target.name == "dev" -%}
          {{ env_var('SNOWFLAKE_SCHEMA') }}
        {%- else -%}
          BUSINESS_CORE
        {%- endif -%}
      dimensions:
        +tags: bc_dimension
      facts:
        +tags: bc_fact
    60_marts:
      +materialized: table
      +schema: >
        {%- if target.name == "dev" -%}
          {{ env_var('SNOWFLAKE_SCHEMA') }}
        {%- else -%}
          MARTS
        {%- endif -%}

## Snapshots
snapshots:
  tasty_bytes:
    +target_schema: >
      {%- if target.name == "dev" -%}
        {{ env_var('SNOWFLAKE_SCHEMA') }}
      {%- else -%}
        HISTORIZED_LANDING
      {%- endif -%}
